-- RGMC Gateway — Brands Seed Data
-- Table already exists with columns: brand_id, brand_code, brand_name, brand_desc, brand_initial
-- Run this in the Supabase SQL Editor to seed the brands

INSERT INTO public.brands (brand_code, brand_name, brand_initial, brand_desc) VALUES
  ('MRDS',    'MY RUNWAY',              'MR', 'Women''s fashion brand under RGMC Group'),
  ('WT',      'WHARTON',                'WT', 'Premium fashion label for men and women'),
  ('DS',      'DANSEN',                 'DS', 'Contemporary casual wear brand'),
  ('WTA',     'WHARTON ACCESSORIES',    'WA', 'Fashion accessories line under Wharton'),
  ('WTLG',    'WHARTON LEATHER GOODS',  'WL', 'Leather goods and bags under Wharton'),
  ('PX',      'PAR EXCELLENCE',         'PX', 'Upscale fashion label'),
  ('WTR',     'WHARTON RAJO',           'WR', 'Wharton collaboration with designer Rajo Laurel'),
  ('UD',      'UBERTO DURANTI',         'UD', 'Italian-inspired fashion brand'),
  ('PD',      'PAPERDOLLS',             'PD', 'Young women''s fashion brand'),
  ('MLY',     'MILLY BY PAPERDOLLS',    'ML', 'Milly sub-brand under Paperdolls'),
  ('SP',      'SCOOP PROJ.',            'SP', 'Contemporary streetwear project brand'),
  ('PDC',     'PD & CO',                'PC', 'Paperdolls companion brand'),
  ('MN',      'MADISON',                'MN', 'Classic American-inspired fashion brand'),
  ('AE',      'APPLE & EVE',            'AE', 'Children''s and young adult fashion brand'),
  ('CS',      'CHATEAU DE SABLE',       'CS', 'French-inspired children''s wear brand'),
  ('DH',      'HECHTER PARIS',          'DH', 'Paris-licensed fashion brand'),
  ('RI',      'RICHELL',                'RI', 'Baby and toddler products brand'),
  ('CC',      'CUDDLE CO',              'CC', 'Infant and toddler comfort products brand'),
  ('TS',      'TWISTSHAKE',             'TS', 'Swedish baby care and feeding products brand'),
  ('EC',      'MRDS-ECONTAINER',        'EC', 'My Runway e-commerce container brand'),
  ('ANHO',    'ALVITA HEAD OFFICE',     'AH', 'Alvita distribution head office'),
  ('ANKI',    'ALVITA KITANLAD',        'AK', 'Alvita Kitanlad distribution branch'),
  ('ANDE',    'ALVITA DELCO',           'AD', 'Alvita Delco distribution branch'),
  ('CGIHO',   'COVENT HEAD OFFICE',     'CH', 'Covent Garden International head office'),
  ('CGIKI',   'COVENT KITANLAD',        'CK', 'Covent Kitanlad distribution branch'),
  ('CGIDE',   'COVENT DELCO',           'CD', 'Covent Delco distribution branch'),
  ('KWHO',    'KEYWEST HEAD OFFICE',    'KH', 'Keywest head office operations'),
  ('KWKI',    'KEYWEST KITANLAD',       'KK', 'Keywest Kitanlad distribution branch'),
  ('KWDE',    'KEYWEST DELCO',          'KD', 'Keywest Delco distribution branch'),
  ('LGHO',    'LEVANT HEAD OFFICE',     'LH', 'Levant head office operations'),
  ('LGKI',    'LEVANT KITANLAD',        'LK', 'Levant Kitanlad distribution branch'),
  ('LGDE',    'LEVANT DELCO',           'LD', 'Levant Delco distribution branch'),
  ('RFHO',    'RICHFIELD HEAD OFFICE',  'RH', 'Richfield head office operations'),
  ('RFKI',    'RICHFIELD KITANLAD',     'RK', 'Richfield Kitanlad distribution branch'),
  ('RRFDE',   'RICHFIELD DELCO',        'RD', 'Richfield Delco distribution branch'),
  ('USGIHO',  'USGI HEAD OFFICE',       'UH', 'USGI head office operations'),
  ('USGIKI',  'USGI KITANLAD',          'UK', 'USGI Kitanlad distribution branch'),
  ('USGIDE',  'USGI DELCO',             'UE', 'USGI Delco distribution branch'),
  ('SBICHO',  'SBIC HEAD OFFICE',       'SH', 'SBIC head office operations'),
  ('SBICDE',  'SBIC DELCO',             'SD', 'SBIC Delco distribution branch'),
  ('VDHO',    'VERIZON HEAD OFFICE',    'VH', 'Verizon Delco head office'),
  ('VDKI',    'VERIZON KITANLAD',       'VK', 'Verizon Kitanlad distribution branch'),
  ('VDDE',    'VERIZON DELCO',          'VD', 'Verizon Delco distribution branch'),
  ('SBICMDSE','SBIC MERCHANDISERS',     'SM', 'SBIC merchandising operations'),
  ('CG-EC',   'CGI-ECONTAINER',         'CE', 'Covent Garden International e-commerce container'),
  ('TH',      'TREEHOUSE',              'TH', 'Children''s lifestyle and fashion brand'),
  ('RGMCHO',  'RGMC HEAD OFFICE PASIG', 'HO', 'RGMC Group main head office in Pasig'),
  ('TN',      'TERRA NOVA',             'TN', 'Outdoor and nature-inspired lifestyle brand'),
  ('TA',      'TELUMO',                 'TA', 'Healthcare and medical products brand'),
  ('MA',      'MARIMER',                'MA', 'French seawater nasal care products brand')
ON CONFLICT (brand_code) DO NOTHING;
